config/routes.rb
RentCentral::Application.routes.draw do
  get "sessions/new"

     resources :listings do
       resources :comments
       resources :listing_images
     end
     resources :users
     resources :sessions, :only => [:new, :create, :destroy]

     match "/" => "listings#home"
     match "/landing" => "listings#landing"
     match "/signup" => "users#new"
     match "/signin" => "sessions#new"
     match "/signout" => "sessions#destroy"
     match "/watch" => "listings#watch"
     match "/change_active" => "listings#change_active"
     match "/change_public" => "listings#change_public"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :listing
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :watchers, :class_name => "User", :foreign_key => "watched_listing_id", :association_foreign_key => "watcher_id"
  has_many :comments
  has_many :listing_images, :dependent => :destroy

  accepts_nested_attributes_for :listing_images
end

app/models/listing_image.rb
class ListingImage < ActiveRecord::Base
  belongs_to :listing
  has_attached_file :photo, :styles => { :small => "200x200" }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :listings
  has_and_belongs_to_many :watched_listings, :class_name => "Listing", :foreign_key => "watcher_id", :association_foreign_key => "watched_listing_id"

  attr_accessor :password
  attr_accessible :name, :email, :phone, :password, :password_confirmation

  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private
    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end



  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6 .. 40  }
  validates :name, :presence => true,
                   :length => { :maximum => 50 }
  validates :email, :presence => true,
                    :uniqueness => { :case_sensitive => false }



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @listing = Listing.find(params[:listing_id])
    if params[:comment][:author] == "" || params[:comment][:body] == ""
      redirect_to listing_path(@listing)
    else
      @comment = @listing.comments.create(params[:comment])
      @comment.post_time = Time.now
      @comment.save!
      redirect_to listing_path(@listing)
    end
  end
end

app/controllers/listing_images_controller.rb
class ListingImagesController < ApplicationController
  def create
    @listing = Listing.find(params[:listing_id])
    if !params[:listing_image][:photo]
      redirect_to listing_path(@listing)
    else
      @listing_image = @listing.listing_images.create!(params[:listing_image])
      redirect_to listing_path(@listing)
    end
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def home
  end
  def index
    sort = params[:sort]
    case sort
    when 'rent'
      ordering = "rent ASC"
    when 'rooms'
      ordering = "number_bedrooms ASC"
    end
    if params[:minRent] == ""
      params[:minRent] = nil
    end
    if params[:maxRent] == ""
      params[:maxRent] = nil
    end
    if params[:minRooms] == ""
      params[:minRooms] = nil
    end
    if params[:maxRooms] == ""
      params[:maxRooms] = nil
    end
    minRent = params[:minRent] || -2147483647
    maxRent = params[:maxRent] || 2147483647
    minRooms = params[:minRooms] || -2147483647
    maxRooms = params[:maxRooms] || 2147483647
    @listings = Listing.find(:all, :conditions => ["rent > ? AND rent < ? AND number_bedrooms > ? AND number_bedrooms < ?", minRent, maxRent, minRooms, maxRooms], :order => ordering)
    @listings = @listings.find_all{|l| l.is_public && l.is_active}
  end

  def show
    id = params[:id]
    @listing = Listing.find(id)
  end

  def new
    @listing = Listing.new
  end

  def create
    if !signed_in?
      flash[:notice] = "You must be signed in to post a listing"
      redirect_to signin_path
    else
      listingParams = params[:listing]
      @listing = current_user.listings.create(listingParams)
      flash[:notice] = "Your listing has been created"
      redirect_to listing_path(@listing)
    end
  end

  def change_public
    @listing = Listing.find params[:id]
    @listing.is_public = !@listing.is_public
    @listing.save!
    redirect_to listing_path(@listing)
  end

  def change_active
    @listing = Listing.find params[:id]
    @listing.is_active = !@listing.is_active
    @listing.save!
    redirect_to listing_path(@listing)
  end

  def watch
    @listing = Listing.find params[:id]
    if !(@listing.watchers.include?(current_user))
      @listing.watchers << current_user
      @listing.save!
    end
    if !(current_user.watched_listings.include?(@listing))
      current_user.watched_listings << @listing
      current_user.save!
    end
    redirect_to listing_path(@listing)
  end

  def edit
    @listing = Listing.find params[:id]
  end

  def update
    @listing = Listing.find params[:id]
    if @listing.user.id != current_user.id
      redirect_to listings_path(@listing)
    else
      @listing.update_attributes!(params[:listing])
      flash[:notice] = "Your listing has been updated"
      redirect_to listings_path(@listing)
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    if @listing.user.id != current_user.id
      redirect_to listings_path
    else
      @listing.destroy
      flash[:notice] = "Your listing has been deleted"
      redirect_to listings_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password"
      render "new"
    else
      sign_in user
      redirect_to user
    end
  end

  def destroy
    sign_out
    redirect_to listings_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = Users.find(:all)
  end

  def show
    id = params[:id]
    @user = User.find(id)
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Your account was successfully created"
      redirect_to @user
    else
      render 'new'
    end
  end

  def new
    @user = User.new

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  private
    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

    def signed_in?
      !current_user.nil?
    end
end

app/views/layouts/application.html.haml
%html
  %head
    -if request.fullpath == '/'
      :javascript
        <!-- Google Website Optimizer Control Script -->
        function utmx_section(){}function utmx(){}
        (function(){var k='0570481186',d=document,l=d.location,c=d.cookie;function f(n){
        if(c){var i=c.indexOf(n+'=');if(i>-1){var j=c.indexOf(';',i);return escape(c.substring(i+n.length+1,j<0?c.length:j))}}}var x=f('__utmx'),xx=f('__utmxx'),h=l.hash;
        d.write('<sc'+'ript src="'+'http'+(l.protocol=='https:'?'s://ssl':'://www')+'.google-analytics.com'+'/siteopt.js?v=1&utmxkey='+k+'&utmx='+(x?x:'')+'&utmxx='+(xx?xx:'')+'&utmxtime='+new Date().valueOf()+(h?'&utmxhash='+escape(h.substr(1)):'')+'" type="text/javascript" charset="utf-8"></sc'+'ript>')})();
      :javascript
        utmx("url",'A/B');
        <!-- End of Google Website Optimizer Control Script -->
        <!-- Google Website Optimizer Tracking Script -->
      :javascript
        var _gaq = _gaq || [];
        _gaq.push(['gwo._setAccount', 'UA-30636490-2']);
        _gaq.push(['gwo._trackPageview', '/0570481186/test']);
        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
        <!-- End of Google Website Optimizer Tracking Script -->
    -if request.fullpath == '/landing'
      :javascript
        <!-- Google Website Optimizer Tracking Script -->
        var _gaq = _gaq || [];
        _gaq.push(['gwo._setAccount', 'UA-30636490-2']);
        _gaq.push(['gwo._trackPageview', '/0570481186/test']);
        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
         <!-- End of Google Website Optimizer Tracking Script -->
    
    - if request.fullpath == '/signup'
      :javascript
        <!-- Google Website Optimizer Tracking Script -->
        var _gaq = _gaq || [];
        _gaq.push(['gwo._setAccount', 'UA-30636490-2']);
        _gaq.push(['gwo._trackPageview', '/0570481186/goal']);
        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

      <!-- End of Google Website Optimizer Tracking Script -->

    %title Rent Central
    = stylesheet_link_tag 'reset'
    = stylesheet_link_tag 'style'
    = stylesheet_link_tag 'custom-style'
    = stylesheet_link_tag 'colorbox'
    = stylesheet_link_tag 'noscript'
    = javascript_include_tag 'application'
    = javascript_include_tag 'jquery.min'
    = javascript_include_tag 'scroll'
    = javascript_include_tag 'dropdown'
    = javascript_include_tag 'jquery.colorbox'
    :javascript
      //Login Colorbox
      $(document).ready(function(){				
        $(".login").colorbox({width:"400px"});				
      });

      // Background Slide Setting    
      var scrollSpeed = 50; // speed in milliseconds	
      var current = 0; // set the default position	
      var direction = 'h'; // set the direction
      function bgscroll(){
        current -= 1;  
        $('div#glow-bg-inner').css("backgroundPosition", (direction == 'h') ? current+"px 0" : "0 " + current+"px");   
      }
      setInterval("bgscroll()", scrollSpeed);	
    = csrf_meta_tags
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-30636490-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

  %body
    #container
      #top-container-inner
        #glow-bg-inner
          #menu-wrapper
            #menu-container
              #logo
                = link_to(image_tag("RentCentralLogo.gif", :height => "75%", :width => "100%"), '/')
              #mainmenu
                %ul#menu
                  %li
                    = link_to 'Home', '/'
                  %li
                    = link_to 'All Public Listings', listings_path
                  -if signed_in?
                    %li= link_to 'Post a Listing', new_listing_path
                    %li
                      = link_to 'My Account', current_user
                      %ul
                        %li= link_to 'Logout', signout_path
                  -else
                    %li= link_to 'Post a Listing', signin_path
                    %li= link_to 'Sign in', signin_path
          - if flash[:notice]
            <br><br><br>
            .success= flash[:notice]
          - if flash[:error]
            <br><br><br>
            .error= flash[:error]
          = yield
          
          = debug(params) if Rails.env.development?

app/views/listings/edit.html.haml
#header-container-inner
  #phone-number
  #pagetitle-wrapper
    %h1 Edit Listing
    #breadcumb
  #slideshow-shadow
#content
  .maincontent-inner
    .col-2-2
      = form_for @listing, :html => {:multipart => true} do |f|
        = f.label :title, 'Title'
        = f.text_field 'title'
        = f.label :address, 'Address'
        = f.text_field 'address' 
        = f.label :rent, 'Rent'
        = f.number_field 'rent'
        = f.label :number_bedrooms, 'Bedrooms'
        = f.number_field 'number_bedrooms'
        = f.label :number_bathrooms, 'Bathrooms'
        = f.number_field 'number_bathrooms'
        = f.label :utilities, 'Included Utilities'
        = f.text_field 'utilities'
        = f.label :parking, 'Parking'
        = f.text_field 'parking'
        = f.label :description, 'Enter Details Here'
        = f.text_area 'description', :cols => 80, :rows => 10
        = f.submit 'Post my Listing'
        - f.fields_for :listing_images do |builder|
          - if builder.object.new_record?
            = builder.label :caption, "File Description"
            = builder.text_field :caption
            = builder.file_field :photo

    .col-3
      %h2 Listing Rules - 
      %u1#details
        %li Do not repeat listings - they will be removed
        %li Edit existing listings instead of creating new ones
        %li Addresses can be approximate - map integration is coming soon

app/views/listings/home.html.haml
#header-container-inner
  #phone-number
  #pagetitle-wrapper
    .center
      %h1 Welcome to RentCentral! <br /> Choose an option above to get started.
      #breadcumb
  #slideshow-shadow
#content
  .maincontent-inner
    .col-3
      .center
        %h2
          Post
      <hr>
      %b Create free listings that are
      %u1
        %li Permanent
        %li Publicly searchable
        %li Linked with images and application forms
      <br>
    .col-3
      .center
        %h2
          Communicate
        <hr>
      %b Find your tenants
      %u1
        %li Advertise your universal listing link
        %li Provide contact information on your profile
        %li Respond to comments on your listing
        %li Facilitate roommate searches
    .col-3
      .center
        %h2
          Finalize
        <hr>
      %b Hibernate your listings
      %u1
        %li Mark your listing as inactive
        %li Upload leases and contracts
        %li Reopen your listing when needed

app/views/listings/index.html.haml
#header-container-inner
  #phone-number
  #pagetitle-wrapper
    %h1 All Listings
    #breadcumb Search all public listings
  #slideshow-shadow
#content
  .maincontent-inner
    .col-2-2
      .table-gray
        
        %table.table
          %thead
            %tr
              %th
                = link_to 'Rent', listings_path(:sort => 'rent', :filter => params[:filter])
              %th Title
              %th Address
              %th
                = link_to 'Bedrooms', listings_path(:sort => 'rooms', :filter => params[:filter])
          %tbody
          -odd = 'odd'
          - @listings.each do |listing|
            - if odd == 'odd'
              -odd = ''
            - else
              -odd = 'odd'
            %tr{:class => odd}
              %td= "$" + String(listing.rent)
              %td= link_to listing.title, listing_path(listing)
              %td= listing.address
              %td= listing.number_bedrooms
    .col-3
      %h2 Search Options
      = form_tag listings_path, :method => :get, :id => 'filter_form' do
        Minimum Rent<br>
        = number_field_tag :minRent, params[:minRent]
        <br>Maximum Rent<br>
        = number_field_tag :maxRent, params[:maxRent]
        <br>Minimum Bedrooms<br>
        = number_field_tag :minRooms, params[:minRooms]
        <br>Maximum Bedrooms<br>
        = number_field_tag :maxRooms, params[:maxRooms]
        <br>
        = submit_tag 'Refresh'

app/views/listings/landing.html.haml
#header-container-inner
  #phone-number
  #pagetitle-wrapper
    .center
      %h1 Welcome to RentCentral!
      #breadcumb
  #slideshow-shadow
#content
  .maincontent-inner
    .col-3
      .center
        %h2
          = link_to 'Post', new_listing_path
      <hr>
      %b Create free listings that are
      %u1
        %li Permanent
        %li Publicly searchable
        %li Linked with images and application forms
      <br>
    .col-3
      .center
        %h2
          = link_to 'Communicate', listings_path
        <hr>
      %b Find your tenants
      %u1
        %li Advertise your universal listing link
        %li Provide contact information on your profile
        %li Respond to comments on your listing
        %li Facilitate roommate searches
    .col-3
      .center
        %h2
          = link_to 'Finalize', current_user
        <hr>
      %b Hibernate your listings
      %u1
        %li Mark your listing as inactive
        %li Upload leases and contracts
        %li Reopen your listing when needed

app/views/listings/new.html.haml
#header-container-inner
  #phone-number
  #pagetitle-wrapper
    %h1 Create a New Listing
    #breadcumb
  #slideshow-shadow
#content
  .maincontent-inner
    .col-2-2
      = form_for @listing, :html => {:multipart => true} do |f|
        = f.label :title, 'Title'
        = f.text_field 'title'
        = f.label :address, 'Address'
        = f.text_field 'address' 
        = f.label :rent, 'Rent'
        = f.number_field 'rent'
        = f.label :number_bedrooms, 'Bedrooms'
        = f.number_field 'number_bedrooms'
        = f.label :number_bathrooms, 'Bathrooms'
        = f.number_field 'number_bathrooms'
        = f.label :utilities, 'Included Utilities'
        = f.text_field 'utilities'
        = f.label :parking, 'Parking'
        = f.text_field 'parking'
        = f.label :description, 'Enter Details Here'
        = f.text_area 'description', :cols => 80, :rows => 10
        = f.submit 'Post my Listing'

        = f.fields_for :listing_images do |builder|
          = builder.label :caption, "File Description"
          = builder.text_field :caption
          = builder.file_field :photo

    .col-3
      %h2 Listing Rules -
      %u1#details
      %u1#details
        %li Do not duplicate listings - they will be removed
        %li Addresses can be approximate - map integration is coming soon
        %li Images can be uploaded after your listing is created

app/views/listings/show.html.haml
#header-container-inner
  #phone-number
  #pagetitle-wrapper
    %h1 
      = @listing.title
    #breadcumb 
      = @listing.address
  #slideshow-shadow
#content
  .maincontent-inner
    .col-3
      %h2 Summary
      - if !@listing.is_active
        <i>This listing is currently inactive</i><br>
      - if !@listing.is_public
        <i>This is a private listing</i><br><br>
      Details
      %u1#details
        %li
          Posted By:
          = link_to @listing.user.name, user_path(@listing.user)
        %li
          Rent:
          = @listing.rent
        %li
          Bedrooms:
          = @listing.number_bedrooms
        %li
          Bathrooms:
          = @listing.number_bathrooms
        %li
          Utilities:
          = @listing.utilities
        %li
          Parking:
          = @listing.parking
        <br>
        - if @listing.watchers.length == 1
          %h4= String(@listing.watchers.length) + " Watcher:"
        - else
          %h4= String(@listing.watchers.length) + " Watchers:"
        - @listing.watchers.each do |watcher|
          = link_to watcher.name, user_path(watcher)
          <br>
      - if signed_in? && !current_user.watched_listings.include?(@listing) && @listing.user != current_user
        = button_to 'Watch this listing', {:controller => "listings", :action => "watch", :id => params[:id]}
      - if signed_in? && @listing.user.id == current_user.id
        <br>
        %h4 Options
        - if @listing.is_active
          = button_to 'Suspend this listing', {:controller => "listings", :action => "change_active", :id => params[:id]}
        - else
          = button_to 'Reactivate this listing', {:controller => "listings", :action => "change_active", :id => params[:id]}
        - if @listing.is_public
          = button_to 'Make this listing private', {:controller => "listings", :action => "change_public", :id => params[:id]}
        - else
          = button_to 'Make this listing public', {:controller => "listings", :action => "change_public", :id => params[:id]}
        = button_to 'Edit this listing', edit_listing_path(@listing), :method => :get
        = button_to 'Delete', listing_path(@listing), :method => :delete, :confirm => 'Are you sure?'
    .col-2-2
      %h2 Description
      %p#description
      = @listing.description
      <hr>
      %h4 Photos
      - @listing.listing_images.each do |li|
        = link_to (image_tag li.photo.url(:small)), li.photo.url

      - if signed_in? && @listing.user.id == current_user.id
        %h4 Upload a photo
        = form_for([@listing, @listing.listing_images.build]) do |f|
          = f.label :caption, "File Description"
          = f.text_field :caption
          = f.file_field :photo
          = f.submit "Upload New Photo"
      <hr>
      %h4 Comments
      - @listing.comments.each do |comment|
        - if comment.author != nil && comment.post_time != nil && comment.body != nil
          = "Posted by \"" + comment.author + "\" at " + (comment.post_time.to_s)[0,20]
          <br>
          = comment.body
      <hr>
      = form_for([@listing, @listing.comments.build]) do |f|
        = f.label :author
        = f.text_field :author
        <br>
        = f.label :body
        = f.text_area :body, :cols => "60", :rows => "5"
        <br>
        = f.submit "Post my Comment"

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  Please fix the following errors to continue
  %ul
  - @user.errors.full_messages.each do |msg|
    %li= msg
  <br>

app/views/users/new.html.haml
#header-container-inner
  #phone-number
  #pagetitle-wrapper
    %h1 Signup
    #breadcumb
  #slideshow-shadow
#content
  .maincontent-inner
    .col-2-2
      = form_for (@user) do |f|
        = render 'shared/error_messages'
        .field
          = label :user, :name, 'Username'
          = text_field :user, 'name'
        .field
          = label :user, :email, 'Email Address'
          = text_field :user, 'email' 
        .field
          = label :user, :phone, 'Phone Number (optional)'
          = text_field :user, 'phone'
        .field
          = label :user, :password, 'Password'
          = password_field :user, 'password'
        .field
          = label :user, :password_confirmation, 'Confirm Password'
          = password_field :user, 'password_confirmation'
        <br>
        = submit_tag 'Sign up!'
    .col-3
      %h2 User Rules
      %u1#details
        %li RentCentral is still in a prototyping stage
        %li Only provide contact information that you wish to be publicly visible - future iterations of this website will provide privacy options.

app/views/users/show.html.haml
#header-container-inner
  #phone-number
  #pagetitle-wrapper
    %h1 
      = @user.name
    #breadcumb 
      = @user.email
      |
      = @user.phone
  #slideshow-shadow
#content
  .maincontent-inner
    .col-2
      %h2 Posted Listings
      .table-gray
        %table.table
          %thead
            %tr
              %th Rent
              %th Title
              %th Address
              %th Bedrooms
          %tbody
          -odd = 'odd'
          - @user.listings.each do |listing|
            - if odd == 'odd'
              -odd = ''
            - else
              -odd = 'odd'
            %tr{:class => odd}
              %td= "$" + String(listing.rent)
              %td= link_to listing.title, listing_path(listing)
              %td= listing.address
              %td= listing.number_bedrooms

    .col-2
      %h2 Watched Listings
      .table-gray
        %table.table
          %thead
            %tr
              %th Rent
              %th Title
              %th Address
              %th Bedrooms
          %tbody
          -odd = 'odd'
          - @user.watched_listings.each do |listing|
            - if odd == 'odd'
              -odd = ''
            - else
              -odd = 'odd'
            %tr{:class => odd}
              %td= "$" + String(listing.rent)
              %td= link_to listing.title, listing_path(listing)
              %td= listing.address
              %td= listing.number_bedrooms